source 'http://rubygems.org'

gem 'cucumber', '~> 3.1.2'
gem 'rspec', '~> 3.11.0'
gem 'selenium-cucumber', '~> 3.1.5'
gem 'appium_lib', '~> 11.2.0'
gem 'parallel_tests', '~> 3.12.0'
gem 'rake', '~> 13.0'
